### ISSUE TITLE
Add core utilities for locking and unlocking MW

### ISSUE THREAD

**Issue by ghost** [inblockio/docker-mediawikibackup#1]
MediaWiki requires a lock during DB procedures to ensure backups are clean. Backup-related utilities should live together and be DRY so move them here and leverage them as needed elsewhere in the codebase.

**Note:** We should also be DRY with the way we source scripts from one another. This means moving reusable code into a utility package within the codebase and sourcing it as needed within other scripts, e.g. a utility functions to lock/unlock WikiMedia may be used within the database backup pre/post commands and other related scripts.

Examples of sourcing scripts from other scripts within a codebase:
- [Existing example](https://github.com/inblockio/MediaWiki_Backup/blob/00c910d6a79d439450a022fca513e256315c82cd/toggle_read_only_off.sh) in codebase and via @rht yesterday
- Another approach: https://stackoverflow.com/a/12694189
- Related reading: [How do I determine the location of my script? I want to read some config files from the same place.
](http://mywiki.wooledge.org/BashFAQ/028) — Covers the gotchas of `$PWD` and `$0` for _bundled_ software

**Comment by 0xc0000007b** [comment]
Examples of sourcing scripts from other scripts within a codebase:
- Existing in codebase and via @rht yesterday https://github.com/inblockio/MediaWiki_Backup/blob/00c910d6a79d439450a022fca513e256315c82cd/toggle_read_only_off.sh
- Another approach: https://stackoverflow.com/a/12694189

**Comment by 0xc0000007b** [comment]
https://loader.sourceforge.io/

<img width="340" alt="Screen Shot 2021-12-04 at 12 40 52 PM" src="https://user-images.githubusercontent.com/94251352/144697255-57bf2846-5619-4c5e-bf82-17ce7b43f729.png">

Considering the above. See [related shellcheck issue](https://github.com/koalaman/shellcheck/issues/1975) for addressing squigglies.
